// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rad2021ConsoleApp.Data;

#nullable disable

namespace Rad2021ConsoleApp.Migrations
{
    [DbContext(typeof(Rad2022Context))]
    partial class Rad2022ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rad2021ClassLibrary.Models.Loans", b =>
                {
                    b.Property<int>("LoanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanID"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<bool>("RepaidInFull")
                        .HasColumnType("bit");

                    b.HasKey("LoanID");

                    b.HasIndex("MemberID");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            LoanID = 1,
                            ApplicationDate = new DateTime(2020, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = false,
                            LoanAmount = 67.00m,
                            MemberID = 1,
                            RepaidInFull = false
                        },
                        new
                        {
                            LoanID = 2,
                            ApplicationDate = new DateTime(2020, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovalDate = new DateTime(2020, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = true,
                            ApprovedBy = "Paul",
                            LoanAmount = 315.00m,
                            MemberID = 1,
                            RepaidInFull = true
                        },
                        new
                        {
                            LoanID = 3,
                            ApplicationDate = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovalDate = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = true,
                            ApprovedBy = "Paul",
                            LoanAmount = 2089.00m,
                            MemberID = 2,
                            RepaidInFull = false
                        },
                        new
                        {
                            LoanID = 4,
                            ApplicationDate = new DateTime(2020, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = false,
                            LoanAmount = 6000.00m,
                            MemberID = 3,
                            RepaidInFull = false
                        },
                        new
                        {
                            LoanID = 5,
                            ApplicationDate = new DateTime(2020, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = false,
                            LoanAmount = 157.00m,
                            MemberID = 4,
                            RepaidInFull = false
                        },
                        new
                        {
                            LoanID = 6,
                            ApplicationDate = new DateTime(2020, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApprovalDate = new DateTime(2020, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Approved = true,
                            ApprovedBy = "Bill",
                            LoanAmount = 4205.00m,
                            MemberID = 5,
                            RepaidInFull = false
                        });
                });

            modelBuilder.Entity("Rad2021ClassLibrary.Models.Members", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoanID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ShareBalance")
                        .HasColumnType("float");

                    b.HasKey("MemberID");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            Address = "8 Johnston Road, Dublin",
                            LoanID = 0,
                            Name = "Elizabeth Anderson",
                            Phone = "(01)-12345322",
                            ShareBalance = 200.0
                        },
                        new
                        {
                            MemberID = 2,
                            Address = "Garden House Crowther Way, Dublin 20",
                            LoanID = 0,
                            Name = "Catherine Autier Miconi",
                            Phone = "(01)-62634562",
                            ShareBalance = 400.0
                        },
                        new
                        {
                            MemberID = 3,
                            Address = "1900 Oak St., Dublin 4",
                            LoanID = 0,
                            Name = "Thomas Axen",
                            Phone = "(01)-89377483",
                            ShareBalance = 2000.0
                        },
                        new
                        {
                            MemberID = 4,
                            Address = "8 Johnston Road, Dublin",
                            LoanID = 0,
                            Name = "John B. Aird",
                            Phone = "(01)-12345322",
                            ShareBalance = 800.0
                        },
                        new
                        {
                            MemberID = 5,
                            Address = "8 Johnston Road, Dublin",
                            LoanID = 0,
                            Name = "Elizabeth Anderson",
                            Phone = "(01)-12345322",
                            ShareBalance = 600.0
                        },
                        new
                        {
                            MemberID = 6,
                            Address = "8 Johnston Road, Dublin",
                            LoanID = 0,
                            Name = "Elizabeth Anderson",
                            Phone = "(01)-12345322",
                            ShareBalance = 3000.0
                        },
                        new
                        {
                            MemberID = 7,
                            Address = "8 Johnston Road, Dublin",
                            LoanID = 0,
                            Name = "Elizabeth Anderson",
                            Phone = "(01)-12345322",
                            ShareBalance = 5000.0
                        });
                });

            modelBuilder.Entity("Rad2021ClassLibrary.Models.Loans", b =>
                {
                    b.HasOne("Rad2021ClassLibrary.Models.Members", "Member")
                        .WithMany("Loan")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Rad2021ClassLibrary.Models.Members", b =>
                {
                    b.Navigation("Loan");
                });
#pragma warning restore 612, 618
        }
    }
}
